"""Generate an httpx client from the derived model.

Reads `AnalysisResult` and nothing else. It never sees the event log, so it
cannot embed a captured value even by accident -- the derived model holds
schema shapes, parameter names and header NAMES, and the one place captured
values appear is `examples`, which this deliberately does not emit into code.

Three rules, each of which was a real defect in the retired generator:

1. **No captured credentials.** The client asks for them from the environment.
   The retired one promised this in a docstring with nothing enforcing it.
2. **TLS verification is never disabled.** A generated client that turns
   verification off to "just work" against a staging cert teaches the reader
   to ship that.
3. **Every method says how much it rests on.** A route observed once is a
   guess about an API; a route observed forty times is a description of one.
   Reading those the same way is how a developer builds on sand.

The output is a starting point, not a specification. It describes one observed
session, which is a subset of the application by definition.
"""

from __future__ import annotations

import keyword
import re
from datetime import UTC, datetime

from ..analysis.models import AnalysisResult, Endpoint

HEADER = '''"""HTTP client for {name}, generated by ScriptScrap.

GENERATED FILE -- derived from what was OBSERVED in one investigation session.
Session: {session}
Generated: {when}

This is a starting point, not a specification. It describes {count} route(s)
that were exercised while an operator drove the application by hand. Routes
nobody visited are not here, and a parameter nobody varied is inferred from a
single value's shape.

CREDENTIALS ARE NOT IN THIS FILE.
{credentials}
Supply them at runtime:

    export SCRIPTSCRAP_AUTH_HEADERS='{{"Cookie": "..."}}'

Nothing in this file was read from the captured session's credential values;
the capture records credential-bearing headers by name only.
"""

from __future__ import annotations

import json
import os
from typing import Any

import httpx

BASE_URL = os.environ.get("SCRIPTSCRAP_BASE_URL", "")


def _auth_headers() -> dict[str, str]:
    """Credential headers, from the environment.

    Empty is a legitimate state -- an unauthenticated route works without
    them -- so this returns {{}} rather than raising, and a 401 tells you
    which one you actually needed.
    """
    raw = os.environ.get("SCRIPTSCRAP_AUTH_HEADERS", "")
    if not raw:
        return {{}}
    try:
        parsed = json.loads(raw)
    except ValueError as exc:
        raise SystemExit(
            "SCRIPTSCRAP_AUTH_HEADERS is not valid JSON: " + str(exc)) from None
    return {{str(k): str(v) for k, v in parsed.items()}}


def _verify() -> bool:
    """TLS verification. Deliberately not configurable.

    A flag here would be used, and a client that skips verification against a
    staging certificate is a client that ships that way.
    """
    return True


class {classname}:
    """Observed routes. Every method names its evidence."""

    def __init__(self, base_url: str = "", *, timeout: float = 30.0) -> None:
        self.base_url = (base_url or BASE_URL).rstrip("/")
        if not self.base_url:
            raise ValueError(
                "no base URL: pass one, or set SCRIPTSCRAP_BASE_URL")
        self._client = httpx.AsyncClient(
            verify=_verify(), timeout=timeout, headers=_auth_headers())

    async def __aenter__(self) -> "{classname}":
        return self

    async def __aexit__(self, *exc: object) -> None:
        await self.aclose()

    async def aclose(self) -> None:
        await self._client.aclose()

    async def _call(self, method: str, path: str, **kwargs: Any) -> httpx.Response:
        return await self._client.request(method, self.base_url + path, **kwargs)
'''

EMPTY_BODY = '''
    # This session observed no endpoints, so there are no methods to generate.
    # That is a statement about the capture, not about the application.
'''


def _identifier(method: str, template: str) -> str:
    """A readable, unique-enough method name from a route."""
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", template) if p]
    cleaned = []
    for part in parts:
        # `{id}` -> `by_id`, so `/items/{id}` reads as `get_items_by_id`.
        cleaned.append(f"by_{part}" if part in _TEMPLATE_NAMES else part)
    name = "_".join([method.lower(), *cleaned]) or f"{method.lower()}_root"
    name = re.sub(r"_+", "_", name).strip("_").lower()
    if not name or name[0].isdigit():
        name = f"call_{name}"
    if keyword.iskeyword(name):
        name = f"{name}_"
    return name


_TEMPLATE_NAMES: set[str] = set()


def _signature(endpoint: Endpoint) -> tuple[list[str], str]:
    """Path holes become required arguments; query params become optional."""
    holes = re.findall(r"\{([^}]+)\}", endpoint.template)
    args: list[str] = []
    path_expr = endpoint.template
    for hole in holes:
        safe = re.sub(r"\W", "_", hole).strip("_") or "value"
        if keyword.iskeyword(safe):
            safe = f"{safe}_"
        args.append(f"{safe}: str")
        path_expr = path_expr.replace(f"{{{hole}}}", f"{{{safe}}}")
    return args, path_expr


def _method(endpoint: Endpoint) -> str:
    args, path_expr = _signature(endpoint)
    query = [p for p in endpoint.params if p.location == "query"]
    takes_body = endpoint.method in {"POST", "PUT", "PATCH"}

    params = ["self", *args]
    if query:
        params.append("*, params: dict[str, Any] | None = None")
    if takes_body:
        params.append("json_body: Any = None" if not query else "json_body: Any = None")

    # ASCII only in generated source: it gets opened in whatever editor the
    # reader has, and a mangled multiplication sign in a docstring is a
    # distraction the generator does not need to create.
    statuses = ", ".join(f"{code} x{n}" for code, n in sorted(endpoint.statuses.items()))
    doc = [
        f"{endpoint.method} {endpoint.template}",
        "",
        f"Observed {endpoint.observation_count}x"
        + (f"; responded {statuses}." if statuses else "."),
    ]
    if endpoint.templated and len(endpoint.concrete_paths) < 2:
        doc += ["",
                "TEMPLATED FROM A SINGLE PATH -- the parameter is inferred from",
                "one value's shape, not from seeing it vary. It may not be a",
                "parameter at all."]
    if endpoint.confidence < 1.0:
        doc += ["", f"Confidence {endpoint.confidence:.0%}."]
    if query:
        doc += ["", "Query parameters observed:"]
        for p in query:
            note = f"{p.name} ({p.inferred_type}, {p.distinct_values} distinct)"
            if p.enum_candidate:
                note += f" one of: {', '.join(map(str, p.enum_candidate))}"
            doc.append(f"  {note}")
    doc += ["", "Evidence: " + ", ".join(endpoint.evidence.event_ids[:8])]

    body = [f"    async def {_identifier(endpoint.method, endpoint.template)}("
            f"{', '.join(params)}) -> httpx.Response:",
            '        """' + "\n        ".join(doc) + '\n        """']

    call = [f'        return await self._call("{endpoint.method}", f"{path_expr}"']
    if query:
        call.append("params=params")
    if takes_body:
        call.append("json=json_body")
    body.append(", ".join(call) + ")")
    return "\n".join(body)


def render_client(result: AnalysisResult, *, session_name: str) -> str:
    """The generated client's source."""
    rest = [e for e in result.endpoints if e.kind == "rest"]

    if result.auth_headers:
        names = ", ".join(sorted(result.auth_headers))
        credentials = (
            f"\nThis application authenticated with credential-bearing header(s): "
            f"{names}.\nThe capture recorded those NAMES and never their values.\n")
    else:
        credentials = (
            "\nNo credential-bearing header was observed on this session's "
            "requests.\n")

    source = HEADER.format(
        name=session_name,
        session=result.session_id,
        when=datetime.now(UTC).isoformat(timespec="seconds"),
        count=len(rest),
        credentials=credentials,
        classname="ObservedApi",
    )

    if not rest:
        return source + EMPTY_BODY

    seen: dict[str, int] = {}
    methods = []
    for endpoint in sorted(rest, key=lambda e: (e.template, e.method)):
        rendered = _method(endpoint)
        name = _identifier(endpoint.method, endpoint.template)
        if name in seen:
            # Two routes can normalise to one name. Suffix rather than drop:
            # losing a route silently is worse than an ugly name.
            seen[name] += 1
            rendered = rendered.replace(
                f"async def {name}(", f"async def {name}_{seen[name]}(", 1)
        else:
            seen[name] = 0
        methods.append(rendered)

    return source + "\n" + "\n\n".join(methods) + "\n"
