"""Generate a Playwright starting point from the derived model.

Walks the transitions that were actually observed, using the highest-stability
locator for each element. Two rules shape the output:

**Every unstable locator is flagged, in place.** A locator below 100% resolved
to zero or several nodes on some observation. Emitting it silently produces a
script that fails mysteriously three steps in; emitting it with its measured
stability beside it tells the reader which line to look at first.

**No assertions.** The session observed what an application DID, never what it
SHOULD do. Generating `assert response.ok` would dress one observation up as a
specification, and a developer would then be maintaining a test that never
tested a requirement.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime

from ..analysis.identifiers import identifier_kind
from ..analysis.models import AnalysisResult, UIElement

HEADER = '''"""Playwright starting point for {name}, generated by ScriptScrap.

GENERATED FILE -- derived from what was OBSERVED in one investigation session.
Session: {session}
Generated: {when}

This is a starting point, not a test. It replays the path an operator actually
walked, using the most stable locator observed for each element. It contains no
assertions: the capture recorded what the application did, never what it should
do, and generating expectations from one observation would turn a recording
into a specification.

What to do with it: run it, watch where it diverges, and turn the steps you
care about into real tests with real expectations.

    pip install playwright && playwright install firefox
    export SCRIPTSCRAP_BASE_URL=https://...
    python {module}.py
"""

from __future__ import annotations

import os

from playwright.sync_api import sync_playwright

BASE_URL = os.environ.get("SCRIPTSCRAP_BASE_URL", "")


def run(page) -> None:
    """The observed workflow, in the order it happened."""
'''

FOOTER = '''

def main() -> None:
    if not BASE_URL:
        raise SystemExit("set SCRIPTSCRAP_BASE_URL to the target's origin")
    with sync_playwright() as p:
        browser = p.firefox.launch(headless=False)
        page = browser.new_page()
        try:
            run(page)
        finally:
            browser.close()


if __name__ == "__main__":
    main()
'''


def _comment_safe(text: object, limit: int = 90) -> str:
    """Collapse captured text to one safe comment line.

    Element labels come from the application: a `<form>`'s accessible name can
    be every option in it, newlines included. Interpolating that into a `#`
    comment ends the comment on the first newline and the rest becomes code,
    so the generated file does not parse. Found by generating from a real
    session, not by inspection.
    """
    flat = " ".join(str(text).split())
    return flat[:limit - 1] + "…" if len(flat) > limit else flat


_VOLATILE_KINDS = {"uuid", "hash"}
_TOKEN_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]*")

# A run of four or more digits. This is the discriminator, arrived at by
# generating from a real capture twice:
#
#   `identifier_kind`'s "code" rule was written for URL path segments, where
#   `ITEM-0001` is data. Inside a CSS selector the same rule matches every
#   utility class a framework ships -- `g-3`, `col-sm-12`, `row-md-6`,
#   `flex-shrink-0` -- and a length threshold does not separate them, because
#   `flex-shrink-0` is longer than `ITEM-0001`.
#
# What does separate them is how many digits: a framework's grid column is one
# or two, while a padded row id or a millisecond timestamp is four or more.
# A warning that fires on Bootstrap is a warning nobody reads, and that would
# cost the genuine UUIDs their audience.
_VOLATILE_DIGITS = re.compile(r"\d{4,}")


def _volatile_tokens(value: str) -> list[str]:
    """Parts of a locator that will not mean the same thing tomorrow.

    A UUID inside a selector is perfectly STABLE within one session -- it
    resolved to one node every time it was observed -- so the stability score
    says nothing is wrong. It is also worthless in every other session. Found by
    generating from a real capture, where two of them reached the script.
    """
    found = []
    for token in _TOKEN_RE.findall(value):
        if identifier_kind(token) in _VOLATILE_KINDS or _VOLATILE_DIGITS.search(token):
            found.append(token)
    return found


def _locator_call(element: UIElement) -> tuple[str, str | None]:
    """The best locator for an element, and a warning if it is not trustworthy.

    Two independent problems, because they fail differently: an unstable
    locator was already ambiguous when it was observed, while a volatile one
    was unambiguous then and will be wrong later.
    """
    if not element.locators:
        return ("page.locator(\"\")", "NO LOCATOR OBSERVED -- fill this in by hand")

    best = max(element.locators, key=lambda locator: locator.stability)
    value = best.value.replace("\\", "\\\\").replace('"', '\\"')

    if best.strategy in {"css", "selector"}:
        call = f'page.locator("{value}")'
    elif best.strategy == "id":
        # The stored value may already be `#name`, depending on how the
        # selector analyser recorded it. Prefixing blindly produced `##name`,
        # which is a valid CSS selector that matches nothing.
        call = f'page.locator("#{value.lstrip("#")}")'
    elif best.strategy in {"test_id", "testid", "data-testid"}:
        call = f'page.get_by_test_id("{value}")'
    elif best.strategy in {"role", "aria_role"}:
        call = f'page.get_by_role("{value}")'
    elif best.strategy in {"label", "aria_label"}:
        call = f'page.get_by_label("{value}")'
    elif best.strategy == "text":
        call = f'page.get_by_text("{value}")'
    else:
        call = f'page.locator("{value}")'

    notes = []
    if best.stability < 1.0:
        notes.append(
            f"UNSTABLE {best.stability:.0%} -- resolved to {best.resolved_count} "
            f"of {best.sample_count} observations"
            + (f"; {best.warning}" if best.warning else ""))

    volatile = _volatile_tokens(best.value)
    if volatile:
        notes.append(
            f"VOLATILE -- contains {', '.join(volatile[:3])}, which looks "
            "session-specific. This locator was stable while it was observed "
            "and will not match in another session.")

    return call, " / ".join(notes) if notes else None


def _action_for(element: UIElement) -> str:
    actions = set(element.actions or [])
    if "submit" in actions:
        return "click"
    if "input" in actions or "change" in actions:
        return "fill"
    return "click"


def render_playwright(result: AnalysisResult, *, session_name: str) -> str:
    """The generated script's source."""
    source = HEADER.format(
        name=session_name,
        session=result.session_id,
        when=datetime.now(UTC).isoformat(timespec="seconds"),
        module="observed_workflow",
    )

    lines: list[str] = []

    entry = next((s for s in result.states if s.url_pattern), None)
    if entry:
        lines.append(f"    # state: {entry.label}")
        lines.append(f'    page.goto(BASE_URL + "{_path_of(entry.url_pattern)}")')
        lines.append("")

    by_key = {e.key: e for e in result.ui_elements}
    steps = 0

    # Walk transitions in the order they were observed, then any element that
    # no transition covered -- a click that changed nothing is still something
    # the operator did, and dropping it would silently shorten the workflow.
    covered: set[str] = set()
    for transition in result.transitions:
        element = by_key.get(transition.trigger)
        target = next((s for s in result.states
                       if s.fingerprint == transition.to_state), None)
        if element is None:
            lines.append("    # observed transition via "
                         f"{_comment_safe(transition.trigger)}, but no element "
                         "was recorded for it")
            if target:
                lines.append(f"    # state: {target.label}")
            lines.append("")
            continue
        covered.add(element.key)
        lines.extend(_step(element, target))
        steps += 1

    for element in result.ui_elements:
        if element.key in covered:
            continue
        lines.extend(_step(element, None))
        steps += 1

    if not steps and not entry:
        lines.append("    # This session reconstructed no states and no interactive")
        lines.append("    # elements, so there is no workflow to replay. That is a")
        lines.append("    # statement about the capture, not the application.")
        lines.append("    return")

    return source + "\n".join(lines) + FOOTER


def _step(element: UIElement, target) -> list[str]:
    call, warning = _locator_call(element)
    action = _action_for(element)
    label = _comment_safe(element.label or element.text or element.key)

    lines = [f"    # {_comment_safe(element.tag, 30)}: {label} "
             f"(observed {element.observation_count}x)"]
    if warning:
        lines.append(f"    # {_comment_safe(warning, 120)}")
    if action == "fill":
        lines.append(f'    {call}.fill("")  # value not recorded; supply your own')
    else:
        lines.append(f"    {call}.click()")
    if target:
        lines.append(f"    # state: {target.label}")
    lines.append("")
    return lines


def _path_of(url_pattern: str) -> str:
    """The path part of a state's URL pattern, so BASE_URL supplies the origin."""
    text = str(url_pattern)
    for scheme in ("https://", "http://"):
        if text.startswith(scheme):
            rest = text[len(scheme):]
            slash = rest.find("/")
            return rest[slash:] if slash >= 0 else "/"
    return text if text.startswith("/") else "/" + text
