"""Generate a Playwright starting point from the derived model.

Walks the transitions that were actually observed, using the highest-stability
locator for each element. Two rules shape the output:

**Every unstable locator is flagged, in place.** A locator below 100% resolved
to zero or several nodes on some observation. Emitting it silently produces a
script that fails mysteriously three steps in; emitting it with its measured
stability beside it tells the reader which line to look at first.

**No assertions.** The session observed what an application DID, never what it
SHOULD do. Generating `assert response.ok` would dress one observation up as a
specification, and a developer would then be maintaining a test that never
tested a requirement.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime

from ..analysis.identifiers import identifier_kind
from ..analysis.models import AnalysisResult, UIElement
from .emit import assert_compiles, py_comment, py_str

HEADER = '''"""Playwright starting point generated by ScriptScrap.

GENERATED FILE -- derived from what was OBSERVED in one investigation session.
Generated: {when}

This is a starting point, not a test. It replays the path an operator actually
walked, using the most stable locator observed for each element. It contains no
assertions: the capture recorded what the application did, never what it should
do, and generating expectations from one observation would turn a recording
into a specification.

What to do with it: run it, watch where it diverges, and turn the steps you
care about into real tests with real expectations.

    pip install playwright && playwright install firefox
    export SCRIPTSCRAP_BASE_URL=https://...
    python {module}.py
"""

from __future__ import annotations

import os

from playwright.sync_api import sync_playwright

BASE_URL = os.environ.get("SCRIPTSCRAP_BASE_URL", "")
'''

# Session identity is captured data, so it goes in a comment below the module
# docstring rather than inside it: a docstring delimiter cannot be escaped.
RUN_PREAMBLE = '''
def run(page) -> None:
    """The observed workflow, in the order it happened."""
'''

FOOTER = '''

def main() -> None:
    if not BASE_URL:
        raise SystemExit("set SCRIPTSCRAP_BASE_URL to the target's origin")
    with sync_playwright() as p:
        browser = p.firefox.launch(headless=False)
        page = browser.new_page()
        try:
            run(page)
        finally:
            browser.close()


if __name__ == "__main__":
    main()
'''


_VOLATILE_KINDS = {"uuid", "hash"}
_TOKEN_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]*")

# A run of four or more digits. This is the discriminator, arrived at by
# generating from a real capture twice:
#
#   `identifier_kind`'s "code" rule was written for URL path segments, where
#   `ITEM-0001` is data. Inside a CSS selector the same rule matches every
#   utility class a framework ships -- `g-3`, `col-sm-12`, `row-md-6`,
#   `flex-shrink-0` -- and a length threshold does not separate them, because
#   `flex-shrink-0` is longer than `ITEM-0001`.
#
# What does separate them is how many digits: a framework's grid column is one
# or two, while a padded row id or a millisecond timestamp is four or more.
# A warning that fires on Bootstrap is a warning nobody reads, and that would
# cost the genuine UUIDs their audience.
_VOLATILE_DIGITS = re.compile(r"\d{4,}")


def _volatile_tokens(value: str) -> list[str]:
    """Parts of a locator that will not mean the same thing tomorrow.

    A UUID inside a selector is perfectly STABLE within one session -- it
    resolved to one node every time it was observed -- so the stability score
    says nothing is wrong. It is also worthless in every other session. Found by
    generating from a real capture, where two of them reached the script.
    """
    found = []
    for token in _TOKEN_RE.findall(value):
        if identifier_kind(token) in _VOLATILE_KINDS or _VOLATILE_DIGITS.search(token):
            found.append(token)
    return found


def _locator_call(element: UIElement) -> tuple[str, str | None]:
    """The best locator for an element, and a warning if it is not trustworthy.

    Two independent problems, because they fail differently: an unstable
    locator was already ambiguous when it was observed, while a volatile one
    was unambiguous then and will be wrong later.
    """
    if not element.locators:
        return (f"page.locator({py_str('')})",
                "NO LOCATOR OBSERVED -- fill this in by hand")

    best = max(element.locators, key=lambda locator: locator.stability)
    value = py_str(best.value)

    if best.strategy in {"css", "selector"}:
        call = f"page.locator({value})"
    elif best.strategy == "id":
        # The stored value may already be `#name`, depending on how the
        # selector analyser recorded it. Prefixing blindly produced `##name`,
        # which is a valid CSS selector that matches nothing.
        call = f"page.locator({py_str('#' + best.value.lstrip('#'))})"
    elif best.strategy in {"test_id", "testid", "data-testid"}:
        call = f"page.get_by_test_id({value})"
    elif best.strategy in {"role", "aria_role"}:
        call = f"page.get_by_role({value})"
    elif best.strategy in {"label", "aria_label"}:
        call = f"page.get_by_label({value})"
    elif best.strategy == "text":
        call = f"page.get_by_text({value})"
    else:
        call = f"page.locator({value})"

    notes = []
    if best.stability < 1.0:
        notes.append(
            f"UNSTABLE {best.stability:.0%} -- resolved to {best.resolved_count} "
            f"of {best.sample_count} observations"
            + (f"; {best.warning}" if best.warning else ""))

    volatile = _volatile_tokens(best.value)
    if volatile:
        notes.append(
            f"VOLATILE -- contains {', '.join(volatile[:3])}, which looks "
            "session-specific. This locator was stable while it was observed "
            "and will not match in another session.")

    return call, " / ".join(notes) if notes else None


def render_playwright(result: AnalysisResult, *, session_name: str) -> str:
    """The generated script's source: the observed workflow, in order."""
    source = HEADER.format(
        when=datetime.now(UTC).isoformat(timespec="seconds"),
        module="observed_workflow",
    )
    source += (f"# session: {py_comment(result.session_id, 100)}\n"
               f"# name:    {py_comment(session_name, 100)}\n")
    source += RUN_PREAMBLE

    by_key = {e.key: e for e in result.ui_elements}
    # First transition per element: a later one is another visit, and naming
    # several destinations for one step would say the step did all of them.
    state_of: dict[str, object] = {}
    for transition in result.transitions:
        if transition.trigger_element_key:
            state_of.setdefault(transition.trigger_element_key, transition)
    label_of = {s.fingerprint: s.label for s in result.states}

    lines: list[str] = []
    for step in result.workflow:
        lines.extend(_step(step, by_key, state_of, label_of))

    if not lines:
        lines = [
            "    # This session recorded no navigation and no user action, so",
            "    # there is no workflow to replay. That is a statement about",
            "    # the capture, not about the application.",
            "    return",
        ]

    return assert_compiles(source + "\n".join(lines) + FOOTER,
                           filename="observed_workflow.py")


def _step(step, by_key, state_of, label_of) -> list[str]:
    """One workflow step. Never more than one call, never fewer."""
    repeat = f" x{step.repeat_count}" if step.repeat_count > 1 else ""
    lines = [f"    # step {step.ordinal}: {step.kind}{repeat}"]

    if step.kind == "navigate":
        lines.append("    page.goto(BASE_URL + "
                     f"{py_str(_path_of(step.url_pattern or '/'))})")
        lines.append("")
        return lines

    element = by_key.get(step.element_key)
    if element is None:
        # The step is real -- the event happened -- but the element it names is
        # not in the derived model, so there is nothing to locate it by.
        lines.append("    # no element was derived for this step; it is "
                     "recorded and cannot be replayed")
        lines.append("")
        return lines

    call, warning = _locator_call(element)
    lines.append(f"    # {py_comment(element.tag, 30)}: "
                 f"{py_comment(element.label or element.text or element.key)} "
                 f"(observed {element.observation_count}x)")
    if warning:
        lines.append(f"    # {py_comment(warning, 120)}")

    action = _action_call(step)
    if action is None:
        lines.append("    # TODO: a key was pressed on this element. The "
                     "capture did not record")
        lines.append("    #       which key, or it was not one this generator "
                     "will reproduce.")
        lines.append(f"    #       Supply it yourself: {call}.press(...)")
    else:
        lines.append(f"    {call}{action}")

    transition = state_of.get(step.element_key)
    if transition is not None:
        target = label_of.get(transition.to_state)
        if target:
            lines.append(f"    # state: {py_comment(target, 80)}")
    lines.append("")
    return lines


def _action_call(step) -> str | None:
    """The Playwright call for one workflow kind, or None if there is none.

    Driven by `WorkflowStep.kind`, which analysis derived from the event type
    and the element. The retired `_action_for` inspected `UIElement.actions`
    -- whose keys are event-type names -- against a vocabulary of bare verbs,
    so every element rendered as a click.

    Returns None for a press whose key was not recorded or not allowlisted.
    There is no call to write: the session did not observe which key, and
    `press("Enter")` would be a keystroke the application never received.
    """
    if step.kind == "fill":
        note = ("  # a value was typed here; its content was not recorded"
                if step.value_recorded else "  # supply your own value")
        return f".fill({py_str('')}){note}"
    if step.kind == "select":
        return (f".select_option({py_str('')})  # the chosen option was not "
                "recorded; supply one")
    if step.kind == "check":
        return ".check()  # observed toggled; check() sets rather than toggles"
    if step.kind == "press":
        if step.key is None:
            return None
        return f".press({py_str(step.key)})"
    return ".click()"


def _path_of(url_pattern: str) -> str:
    """The path part of a state's URL pattern, so BASE_URL supplies the origin."""
    text = str(url_pattern)
    for scheme in ("https://", "http://"):
        if text.startswith(scheme):
            rest = text[len(scheme):]
            slash = rest.find("/")
            return rest[slash:] if slash >= 0 else "/"
    return text if text.startswith("/") else "/" + text
